const data = {
  products: [
    {
      name: 'Bank Shirt',
      slug: 'bank-shirt',
      category: 'Shirts',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQglH2uxK1Lz7Wl9zOryFVUhLjxVH2jppLQdQ&usqp=CAU',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description:
        'A popular shirt A popular shirt A popular shirt A popular shirt  A popular shirt A popular shirtA popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image:
        'https://static01.nyt.com/images/2020/10/29/fashion/26SNEAKERSPILL-coke/merlin_178616208_a26fbc99-1fd8-4e12-a966-daf93009e6ba-articleLarge.jpg?quality=75&auto=webp&disable=upscale',
      price: 80,
      brand: 'Addidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image:
        'https://priyoshopbackup.blob.core.windows.net/priyoshop/content/Images/Thumbs/0235613_leather-half-shoe-for-men-ara10117ofwht_415.jpeg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: ' Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image:
        'https://www.solereview.com/wp-content/uploads/2021/03/Best_shoes_for_standing_all_day-2021.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Diamond Pants',
      slug: 'diamond-pants',
      category: 'Pants',
      image:
        'https://ids.si.edu/ids/deliveryService?max_w=550&id=NMAAHC-2018_58ab_006',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A poupular pants',
    },
    {
      name: 'Fat Pants',
      slug: 'Fat-pants',
      category: 'Pants',
      image:
        'https://res.cloudinary.com/onitshamarket/image/upload/q_auto/f_auto/onitshamarket/product/lcmhnqw2wn2ctazsr4ee.jpg',
      price: 95,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A poupular pants',
    },
    {
      name: 'Jolly Shirt',
      slug: 'jolly-shirt',
      category: 'Shirts',
      image:
        'https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/33/114525/3.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description:
        'A popular shirt A popular shirt A popular shirt A popular shirt  A popular shirt A popular shirtA popular shirt',
    },
    {
      name: 'Fit Trousers',
      slug: 'fit-trousers',
      category: 'Shirts',
      image: 'https://m.media-amazon.com/images/I/61YXZmuiJsL._AC_UY445_.jpg',
      price: 80,
      brand: 'Addidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Trousers',
      slug: 'fit-trousers',
      category: 'Electronics',
      image: 'https://m.media-amazon.com/images/I/61YXZmuiJsL._AC_UY445_.jpg',
      price: 80,
      brand: 'Addidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Bag Shirt',
      slug: 'bag-shirt',
      category: 'Shirts',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTu3OLKYe_R7oiRXTqNvYwdiUKtBGfzNDP2cg&usqp=CAU',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: ' Fear wear',
      slug: 'fear-wear',
      category: 'Pants',
      image: 'https://ngo-shoes.com/1896-large_default/ha-noi.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'fit sports',
      slug: 'fit-sports',
      category: 'Pants',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHPXtHzZTMs_6fx2VWlUMUIykgO0Kw-Q_INgYMVE7AYpkmk5-kYlfspT616F88GFm1wkU&usqp=CAU',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A poupular pants',
    },
    {
      name: 'Men Category',
      slug: 'men-category',
      category: 'Pants',
      image:
        'https://m.media-amazon.com/images/I/51NBXCzEixL._AC._SR360,460.jpg',
      price: 95,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A poupular pants',
    },
    {
      name: 'fas Category',
      slug: 'fas-category',
      category: 'Pants',
      image:
        'https://m.media-amazon.com/images/I/51NBXCzEixL._AC._SR360,460.jpg',
      price: 95,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A poupular pants',
    },
  ],
};

export default data;
